"""created all 3 models

Revision ID: 680276edf916
Revises: 4a6c85779582
Create Date: 2023-12-05 17:22:17.169351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680276edf916'
down_revision = '4a6c85779582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('total_attendees', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('preferred_position', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pickup_game__id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_game__id'], ['pickup_games.id'], name=op.f('fk_player_signups_pickup_game__id_pickup_games')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_player_signups_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_signups')
    op.drop_table('pickup_games')
    # ### end Alembic commands ###
