"""added city and state attributes

Revision ID: d1e889cecb31
Revises: 680276edf916
Create Date: 2023-12-06 00:04:37.623996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e889cecb31'
down_revision = '680276edf916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_games', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
